name: Auto Label Issues

on:
  issues:
    types: [opened]

jobs:
  label-by-keyword:
    runs-on: ubuntu-latest
    steps:
      - name: Label issues based on keywords
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const issue = context.payload.issue;
            const title = issue.title.toLowerCase();
            const body = issue.body.toLowerCase();
            const labels = [];

            if (title.includes('error') || body.includes('error') || body.includes('crash')) {
              labels.push('bug');
            }
            if (title.includes('feature') || body.includes('enhancement')) {
              labels.push('enhancement');
            }
            if (title.includes('docs') || body.includes('documentation')) {
              labels.push('documentation');
            }
            if (title.includes('question') || body.includes('how') || body.includes('why')) {
              labels.push('Questions');
            }

            if (labels.length > 0) {
              await github.rest.issues.addLabels({
                owner: context.repo.owner,
                repo: context.repo.repo,
                issue_number: issue.number,
                labels: labels
              });
            }
